[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "send-email"
  path = "/api/send-email"

[dev]
  framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
