[build]
  command = "echo 'Checking env vars...' && echo 'RESEND_API_KEY present:' $REACT_APP_RESEND_API_KEY && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
